export const SHEETS = {
  job_active: {
    label: 'Job Aktif (WIP)',
    unit: 'Job',
    color: '#0284c7',
    headers: ['id', 'job_name', 'job_no', 'file_no', 'status', 'start_time', 'date', 'category'],
    dataCols: [0, 1, 2, 3, 4, 5, 6, 7],
    i: { 
      id: 0, 
      job_name: 1, 
      jop: 1, 
      job_no: 2, 
      nojop: 2, 
      file_no: 3, 
      status: 4, 
      start_time: 5, 
      date: 6, 
      category: 7 
    }
  },
  rec_ctcp: {
    label: 'CTCP Offset',
    unit: 'Plate',
    color: '#8b5cf6',
    headers: ['id', 'job_name', 'job_no', 'plate_no', 'date', 'expose_mach', 'print_mach', 'paper_type', 'plate_size', 'qty_new', 'qty_replace', 'qty_good', 'qty_defect', 'replace_reason', 'special_request', 'defect_reason', 'notes', 'shift', 'operator', 'po_helper'],
    dataCols: [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 17, 18],
    i: { 
      id: 0, 
      jop: 1, 
      nojop: 2, 
      plate_no: 3, 
      date: 4, 
      expose_mach: 5, 
      print_mach: 6, 
      paper_type: 7, 
      plate_size: 8, 
      qty_new: 9, 
      ganti: 10, 
      qty_replace: 10, 
      baik: 11, 
      qty_good: 11, 
      rusak: 12, 
      qty_defect: 12, 
      penyGanti: 13, 
      replace_reason: 13, 
      special_request: 14, 
      penyRusak: 15, 
      defect_reason: 15, 
      notes: 16, 
      shift: 17, 
      op: 18, 
      operator: 18, 
      po: 19, 
      po_helper: 19 
    },
    cards: { baik: 'Plate Baik', rusak: 'Plate Rusak', ganti: 'Plate Ganti', pakai: 'Total Plate' },
    charts: { daily: 'Output Plate CTCP Harian', extra: { title: 'Mesin Expose', col: 5, kind: 'bar' } }
  },
  rec_ctp: {
    label: 'CTP Thermal',
    unit: 'Plate',
    color: '#10b981',
    headers: ['id', 'job_name', 'job_no', 'plate_no', 'date', 'expose_mach', 'plate_size', 'print_mach', 'paper_type', 'qty_new', 'qty_replace', 'qty_good', 'qty_defect', 'replace_reason', 'special_request', 'defect_reason', 'notes', 'shift', 'operator'],
    dataCols: [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 17, 18],
    i: { 
      id: 0, 
      jop: 1, 
      nojop: 2, 
      plate_no: 3, 
      date: 4, 
      expose_mach: 5, 
      plate_size: 6, 
      print_mach: 7, 
      paper_type: 8, 
      qty_new: 9, 
      ganti: 10, 
      qty_replace: 10, 
      baik: 11, 
      qty_good: 11, 
      rusak: 12, 
      qty_defect: 12, 
      penyGanti: 13, 
      replace_reason: 13, 
      special_request: 14, 
      penyRusak: 15, 
      defect_reason: 15, 
      notes: 16, 
      shift: 17, 
      op: 18, 
      operator: 18, 
      po: -1, 
      po_helper: -1 
    },
    cards: { baik: 'Plate Baik', rusak: 'Plate Rusak', ganti: 'Plate Ganti', pakai: 'Total Plate' },
    charts: { daily: 'Output Plate CTP Harian', extra: { title: 'Ukuran Plate', col: 6, kind: 'doughnut' } }
  },
  rec_screen: {
    label: 'Screen Printing',
    unit: 'Screen',
    color: '#06b6d4',
    headers: ['id', 'job_name', 'job_no', 'file_no', 'screen_type', 'status', 'start_time', 'finish_time', 'duration', 'date', 'description', 'screen_mesh', 'shift', 'notes', 'qty_good', 'qty_defect', 'qty_replace', 'defect_reason', 'replace_reason', 'operator'],
    dataCols: [0, 1, 2, 4, 9, 11, 12, 14, 15, 16, 19],
    i: { 
      id: 0, 
      jop: 1, 
      nojop: 2, 
      file_no: 3, 
      tipe: 4, 
      screen_type: 4, 
      status: 5, 
      start_time: 6, 
      finish_time: 7, 
      duration: 8, 
      date: 9, 
      description: 10, 
      screen_mesh: 11, 
      shift: 12, 
      notes: 13, 
      baik: 14, 
      qty_good: 14, 
      rusak: 15, 
      qty_defect: 15, 
      ganti: 16, 
      qty_replace: 16, 
      penyRusak: 17, 
      defect_reason: 17, 
      penyGanti: 18, 
      replace_reason: 18, 
      op: 19, 
      operator: 19, 
      po: -1, 
      po_helper: -1 
    },
    cards: { baik: 'Screen Baik', rusak: 'Screen Rusak', ganti: 'Screen Ganti', pakai: 'Total Screen' },
    charts: { daily: 'Output Screen Harian', extra: { title: 'Tipe Screen', col: 4, kind: 'doughnut' } }
  },
  rec_flexo: {
    label: 'Flexography',
    unit: 'Plate',
    color: '#6366f1',
    headers: ['id', 'job_name', 'job_no', 'file_no', 'status', 'start_time', 'finish_time', 'duration', 'date', 'description', 'lpi', 'flexo_thickness', 'print_mach', 'rip_pos', 'keterangan', 'notes', 'qty_good', 'qty_defect', 'qty_replace', 'defect_reason', 'replace_reason', 'shift', 'operator', 'po_helper'],
    dataCols: [0, 1, 2, 8, 10, 11, 12, 16, 17, 18, 21, 22, 23],
    i: { 
      id: 0, 
      jop: 1, 
      nojop: 2, 
      file_no: 3, 
      status: 4, 
      start_time: 5, 
      finish_time: 6, 
      duration: 7, 
      date: 8, 
      description: 9, 
      lpi: 10, 
      tebal: 11, 
      flexo_thickness: 11, 
      print_mach: 12, 
      rip_pos: 13, 
      keterangan: 14, 
      notes: 15, 
      baik: 16, 
      qty_good: 16, 
      rusak: 17, 
      qty_defect: 17, 
      ganti: 18, 
      qty_replace: 18, 
      penyRusak: 19, 
      defect_reason: 19, 
      penyGanti: 20, 
      replace_reason: 20, 
      shift: 21, 
      op: 22, 
      operator: 22, 
      po: 23, 
      po_helper: 23 
    },
    cards: { baik: 'Flexo Baik', rusak: 'Flexo Rusak', ganti: 'Flexo Ganti', pakai: 'Total Flexo' },
    charts: { daily: 'Output Flexo Harian', extra: { title: 'Tebal Flexo', col: 11, kind: 'bar' } }
  },
  rec_etching: {
    label: 'Etching Plate',
    unit: 'Plate',
    color: '#f59e0b',
    headers: ['id', 'job_name', 'job_no', 'file_no', 'plate_type', 'status', 'start_time', 'finish_time', 'duration', 'date', 'description', 'plate_thickness', 'keterangan', 'qty_good', 'qty_defect', 'qty_replace', 'defect_reason', 'replace_reason', 'shift', 'operator', 'po_helper'],
    dataCols: [0, 1, 2, 4, 9, 11, 13, 14, 15, 18, 19, 20],
    i: { 
      id: 0, 
      jop: 1, 
      nojop: 2, 
      file_no: 3, 
      tipe: 4, 
      plate_type: 4, 
      status: 5, 
      start_time: 6, 
      finish_time: 7, 
      duration: 8, 
      date: 9, 
      description: 10, 
      tebal: 11, 
      plate_thickness: 11, 
      keterangan: 12, 
      baik: 13, 
      qty_good: 13, 
      rusak: 14, 
      qty_defect: 14, 
      ganti: 15, 
      qty_replace: 15, 
      penyRusak: 16, 
      defect_reason: 16, 
      penyGanti: 17, 
      replace_reason: 17, 
      shift: 18, 
      op: 19, 
      operator: 19, 
      po: 20, 
      po_helper: 20 
    },
    cards: { baik: 'Plate Baik', rusak: 'Plate Rusak', ganti: 'Plate Ganti', pakai: 'Total Plate' },
    charts: { daily: 'Output Etching Harian', extra: { title: 'Tipe Plate', col: 4, kind: 'doughnut' } }
  },
  master_user: {
    label: 'Master Pengguna',
    headers: ['id', 'username', 'role', 'password_hash'],
    dataCols: [0, 1, 2, 3],
    i: { id: 0, username: 1, role: 2, password_hash: 3 }
  }
};

export const FORMS = [
  {
    key: 'rec_ctcp',
    id: 'ctcp',
    label: 'CTCP',
    title: 'CTCP Offset (UV-CTCP)',
    badge: 'UV-CTCP Offset',
    desc: 'Form permintaan pembuatan plate CTCP Offset (UV-CTCP) untuk mesin cetak offset.',
    url: 'https://forms.gle/sjXvX1mQLmfconpaA',
    iconType: 'printer',
    color: '#8b5cf6',
    borderClass: 'border-violet-500/40 hover:border-violet-500',
    bgBadge: 'bg-violet-50 text-violet-700 dark:bg-violet-500/20 dark:text-violet-300'
  },
  {
    key: 'rec_ctp',
    id: 'ctp',
    label: 'CTP',
    title: 'CTP Thermal Plate',
    badge: 'Thermal CTP',
    desc: 'Form permintaan pembuatan plate CTP Thermal berpresisi tinggi tanpa proses kimia basah.',
    url: 'https://forms.gle/Y2iumgVVMk8Ph8Ez8',
    iconType: 'file-text',
    color: '#10b981',
    borderClass: 'border-emerald-500/40 hover:border-emerald-500',
    bgBadge: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300'
  },
  {
    key: 'rec_screen',
    id: 'screen',
    label: 'SCREEN',
    title: 'Screen Printing / Sablon',
    badge: 'Screen Sablon',
    desc: 'Form permintaan afdruk, perbaikan, dan pembuatan master kain Screen Sablon.',
    url: 'https://forms.gle/KUBCCpbE9ocRKUgC9',
    iconType: 'frame',
    color: '#06b6d4',
    borderClass: 'border-cyan-500/40 hover:border-cyan-500',
    bgBadge: 'bg-cyan-50 text-cyan-700 dark:bg-cyan-500/20 dark:text-cyan-300'
  },
  {
    key: 'rec_flexo',
    id: 'flexo',
    label: 'FLEXO',
    title: 'Flexography Photopolymer',
    badge: 'Flexo Plate',
    desc: 'Form permintaan pembuatan plate Polimer Flexography kemasan & label sticker.',
    url: 'https://forms.gle/yux9WXnftA4isDW77',
    iconType: 'package',
    color: '#6366f1',
    borderClass: 'border-indigo-500/40 hover:border-indigo-500',
    bgBadge: 'bg-indigo-50 text-indigo-700 dark:bg-indigo-500/20 dark:text-indigo-300'
  },
  {
    key: 'rec_etching',
    id: 'etching',
    label: 'ETCHING',
    title: 'Etching Plate / Emboss / Foil',
    badge: 'Magnesium / Zinc Etch',
    desc: 'Form permintaan pembuatan plat logam Etching untuk foil emas, emboss, dan deboss.',
    url: 'https://forms.gle/JLu6gVW3qcCv5xvR8',
    iconType: 'sparkles',
    color: '#f59e0b',
    borderClass: 'border-amber-500/40 hover:border-amber-500',
    bgBadge: 'bg-amber-50 text-amber-700 dark:bg-amber-500/20 dark:text-amber-300'
  }
];

export const JOP_CATS = [
  ['O', 'Offset'],
  ['FLEXO', 'Flexo'],
  ['SCREEN', 'Screen'],
  ['ETCHING', 'Etching'],
  ['SAMPLE', 'Sample'],
  ['REPRINT', 'Reprint']
];

export const CAT_COLORS = {
  O: '#8b5cf6',
  FLEXO: '#6366f1',
  SCREEN: '#06b6d4',
  ETCHING: '#f59e0b',
  SAMPLE: '#10b981',
  REPRINT: '#ec4899'
};

export const PROD_KEYS = ['rec_ctcp', 'rec_ctp', 'rec_screen', 'rec_flexo', 'rec_etching'];
export const ALL_KEYS = ['job_active', ...PROD_KEYS, 'master_user'];
export const TABLE_NAMES = ALL_KEYS;