name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - versi-8

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseToken: '${{ secrets.FIREBASE_CLI_TOKEN }}'
          channelId: live
          projectId: prism-ac
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks